### ISSUE TITLE
Comentarios de su documentación

### ISSUE THREAD

**Issue by monzter50** [Caribbean-Analytics/OWO#2]
Hola @Caribbean-Analytics, entiendo por la descripción en el punto de móvil y  web su modelo de negocio pero realmente, solo requiero saber si será una aplicación móvil o web. 

El planteamiento de sus objetivos no cumple con los puntos necesarios, comparto una manera adecuada  de redacción, el objetivo debe reflejar la esencia del planteamiento del problema y la idea expresada, respondiendo las preguntas: ¿Qué? ¿Cómo? ¿Para qué? y En los objetivos específicos se debe desprender del general y deben ser formulados de forma que estén orientados al logro del objetivo general.

**Comment by JFrankgod** [comment]
@monzter50 Que tal profesor, podría verificar si la documentación ya es la correcta. Si no para que la siga verificando.
