### ISSUE TITLE
Infografía UX y UI

### ISSUE THREAD

**Issue by monzter50** [Caribbean-Analytics/OWO#9]
# Elaborar 4 infografía (Individual)
* Habilidades de UX
* Habilidades de UI
* ¿Que es UX y UX?
* Diferencias entre UI y UX

## Fecha limite 07-03-2020 a las 11:59 pm

**Comment by 170300075** [comment]
Profesor, ¿se pueden hacer en Canva?

**Comment by monzter50** [comment]
Hola @170300075  por el momento requiero que se familiaricen con las herramientas editor de gráficos vectoriales pero puedes apoyarte con paginas como flaticon, freepik, svgporn,  etc..

**Comment by 170300075** [comment]
Ok profesor. Una cosa, mi tarea se encuentra en el directorio KennethDiazGonzalez/infografias en la rama 02-design
